# Generated by Django 4.2 on 2023-04-22 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('SURVEY', 'Survey'), ('DISCUSSION', 'Discussion'), ('DIARY', 'Diary')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launch_date', models.DateField()),
                ('status', models.CharField(choices=[('LIVE', 'Live'), ('PENDING', 'Pending'), ('ARCHIVED', 'Archived')], max_length=10)),
                ('tasks', models.ManyToManyField(related_name='tiles', to='tasks.task')),
            ],
        ),
    ]
